### ISSUE TITLE
`ALL_CARGO_DIST_INSTALLER_ARGS` is empty (invalid YAML schema)

### ISSUE THREAD

**Issue by AntoniosBarotsis** [axodotdev/cargo-dist#101]
I ran `cargo dist init --ci=github` for a personal project and everything seems to be working fine except for the `env` declaration at the top

```yaml
env:
  ALL_CARGO_DIST_TARGET_ARGS: --target=x86_64-unknown-linux-gnu --target=x86_64-apple-darwin --target=x86_64-pc-windows-msvc 
  # Current
  ALL_CARGO_DIST_INSTALLER_ARGS: 
  # This would be valid
  ALL_CARGO_DIST_INSTALLER_ARGS: ''
```

This is *technically* invalid YAML `Incorrect type. Expected "string | number | boolean".`, you can check the schema [here](https://json.schemastore.org/github-workflow.json).

The code that generates this can be found [here](https://github.com/axodotdev/cargo-dist/blob/45f8c57d678ba08d4896fb39dc5d963b54817868/cargo-dist/src/ci.rs#L200-L209).
