### ISSUE TITLE
make cargo-dist opt-in for binaries

### ISSUE THREAD

**Issue by NicholasLYang** [axodotdev/cargo-dist#1113]
Hi, we're looking to adopt cargo-dist for releasing Turborepo. However, we share a repository with other projects, and therefore have multiple binaries in the workspace. I noticed that you can opt-out for a binary by setting `publish = false` or `dist = false`.  I was wondering if there's a way to instead make `cargo dist` opt-in by default, so you have to explicitly annotate `publish = true`. That way if someone adds a new binary but forgets to annotate it, we won't publish it by accident.

**Comment by Gankra** [comment]
Indeed, you can! If you set

```toml
[workspace.metadata.dist]
dist = false
```

Then that setting gets inherited by every package, so they have to manually override it with

```toml
[package.metadata.dist]
dist = true
```
