### ISSUE TITLE
`dependencies` for `aarch64-apple-darwin` via `homebrew` incorrect arch by default

### ISSUE THREAD

**Issue by FreeMasen** [axodotdev/cargo-dist#1244]
With a cfg like this

```toml
[workspace.metadata.dist.dependencies.homebrew]
zstd = { stage = ["build", "run"], targets = ["aarch64-apple-darwin"] }

```

With the default settings will actually generate an action that will end up downloading `zstd` compiled for x86 and not aarch64. I am wondering if the brew install script should follow the guidance from [this SO answer](https://stackoverflow.com/a/75488269)?

```sh
# Cross install aarch libs for macos-12
brew fetch --force --bottle-tag=arm64_sonoma <bottle-name>
brew install $(brew --cache --bottle-tag=arm64_sonoma <bottle-name>)
```

If not be default, potentially driven by a new property on the `SystemDependencyComplex`?

**Comment by mistydemeo** [comment]
We're in a somewhat complex situation with dependencies because there's two different things you may want to install them for: either as a commandline tool that you need to run, or as a library you need to link against. In the former case, installing the cross-arch version would actually break the build by providing an executable the host can't execute. (The same package could also contain both an executable and a library, further complicating things.)

While, as you note, it's technically possible to force cross-platform binary installation, this is a bit brittle and could break without notice in future versions of Homebrew. It could also lead to issues with executables as I mentioned. Our preferred solution in this case is to run the build natively - I recommend using the [runner config](https://opensource.axo.dev/cargo-dist/book/ci/customizing.html#custom-runners) to set your runner for aarch64 builds to `macos-14`.

It looks like this is partially, but not fully, documented. I'll make sure to fully document this.

**Comment by FreeMasen** [comment]
What if there was a configuration option for these dependencies like this

```toml
[workspace.metadata.dist.dependencies.homebrew]
zstd = { stage = ["build", "run"], targets = ["aarch64-apple-darwin"], force_bottle_tag = "arm64_sonoma" }
```
That would result in an output like I listed in my initial comment? This would allow users to opt into arch specific library installs? Potentially with the `--no-binaries` option?
