### ISSUE TITLE
Check that linux binaries don't depend on external libraries

### ISSUE THREAD

**Issue by konstin** [axodotdev/cargo-dist#1249]
We recently unintentionally introduced a dependency on a shared library (https://github.com/astral-sh/uv/issues/5572). It would be great if cargo-dist could check during general ci that there are no unintended external dependencies.

Below is the expected correct output, there are some dynamic libraries for gnu (the manylinux policy is a good references) and none for musl.

gnu:
```
$ ldd target/debug/uv
	linux-vdso.so.1 (0x00007fff77ff8000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x000071e1b2a91000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000071e1b2a64000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000071e1b297b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000071e1aea00000)
	/lib64/ld-linux-x86-64.so.2 (0x000071e1b2ae2000)
```

musl:
```
$ ldd target/x86_64-unknown-linux-musl/debug/uv
	statically linked
```

**Comment by mistydemeo** [comment]
This is definitely an interesting idea. We already print linkage information in the output, but the idea of being able to diff from an expected set of dependencies would be a nice enhancement. I can envision a way to specify expected dependencies per-triple in the config, say:

```toml
[workspace.metadata.dist.expected-system-dependencies]
x86_64-unknown-linux-gnu = ["linux-vdso", "liblzma", "libgcc_s", "libm", "libc", "ld-linux-x86-64"]
x86_64-unknown-linux-musl = []
```

And the build fails with an error if our linkage report finds anything that differs from that.
