### ISSUE TITLE
Unchecking homebrew should leave no trace of homebrew

### ISSUE THREAD

**Issue by alexanderjophus** [axodotdev/cargo-dist#1275]
After running `cargo dist init`, I checked homebrew, then later realised I didn't need it yet.

I then ran `cargo dist init` again, unchecked homebrew, however the following was still in my Cargo.toml

```toml
# Config for 'cargo dist'
[workspace.metadata.dist]
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
```

Similarly in CI the following step was still there `publish-homebrew-formula` (and depended on by `announce`

Open to input on whether it should fully take out the CI step - I think it should, but is there the use case of someone editing it and needing the edits later (could they just look at their git history?)

Also, if this is needed, I'd love to try contributing back!
