### ISSUE TITLE
Migrate to config 1.0

### ISSUE THREAD

**Issue by mistydemeo** [axodotdev/cargo-dist#1533]
Internally, we've migrated to the planned 1.0 config format - we parse the original format, then do a conversion to the new structure. The new structure is set up with serialization and deserialization routes that makes it theoretically possible to read the new files - but nothing is set up to actually do so. Our final steps to complete this migration will be:

* Introduce parallel deserialization of both config formats. We need to keep being able to read the old format to report to users that they need to upgrade, and so that we can:
* Use `dist init` to read the old config format and migrate to the new one, and then use that new format as the basis for edits we make to the user's config files on their behalf. This should allow us to painlessly migrate everyone to the new format.

My plan is that when we introduce this, any commands except `init` will refuse to run if they're loaded from the old config files, but can use that as information to notify users that they need to upgrade via `dist init`.

**Comment by mistydemeo** [comment]
I did a quick look at the [`TomlLayer`](https://github.com/axodotdev/cargo-dist/blob/f8e0688ce296ed262d6d4c63c676f62fb5e3e48b/cargo-dist/src/config/v1/mod.rs#L379) to confirm, and we are definitely set for serializing and deserializing it from TOML files. Here's a sample of taking dist's own existing v0 config, passing it through the `TomlLayer` upconversion carousel, and then serializing it to disk.

```toml
dist-version = "0.24.1"
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
]

[[artifacts.extra]]
build = [
    "cargo",
    "run",
    "--release",
    "--",
    "dist",
    "manifest-schema",
    "--output=dist-manifest-schema.json",
]
artifacts = ["dist-manifest-schema.json"]

[ci]
pr-run-mode = "plan"
publish-jobs = ["./publish-crates"]

[ci.github.runners]
aarch64-unknown-linux-gnu = "buildjet-8vcpu-ubuntu-2204-arm"
aarch64-unknown-linux-musl = "buildjet-8vcpu-ubuntu-2204-arm"

[hosts]
axodotdev = true

[hosts.github]
attestations = true

[installers]
install-path = "CARGO_HOME"
powershell = true
shell = true
updater = false

[installers.bin-aliases]
dist = ["cargo-dist"]

[installers.homebrew]
tap = "axodotdev/homebrew-tap"

[installers.npm]
scope = "@axodotdev"

[publishers]
homebrew = true
npm = true
```
