### ISSUE TITLE
Broken ci for aarch64 windows build

### ISSUE THREAD

**Issue by DenuxPlays** [axodotdev/cargo-dist#1633]
See logs here: https://github.com/DenuxPlays/dyncloud/actions/runs/12304496065/job/34342058658

**Comment by mistydemeo** [comment]
Sorry for the inconvenience. I think I know what caused this, and I'm looking into fixing it.

In the meantime, you can fix this by specifying a cargo-xwin container for the aarch64-pc-windows-msvc target:

```toml
[dist.github-custom-runners.aarch64-pc-windows-msvc]
container = "messense/cargo-xwin"
```
