### ISSUE TITLE
Need to update from ubuntu-20.04 runner images

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [axodotdev/cargo-dist#1760]
I just got this email from GitHub:
```
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:


March 4 14:00 UTC – 22:00 UTC
March 11 13:00 UTC – 21:00 UTC
March 18 13:00 UTC – 21:00 UTC
March 25 13:00 UTC – 21:00 UTC
What you need to do

Jobs using the ubuntu-20.04 YAML workflow label should be updated to ubuntu-22.04, ubuntu-24.04 or ubuntu-latest. You can always get up-to-date information on our tools by reading about the software in the [runner images repository](https://app.github.media/e/er?s=88570519&lid=3455&elqTrackId=1befe7689f3c4a1a9cba67758d7c6fa0&elq=c8e2b0ece4644da9b1fbbf27de7f9c73&elqaid=4309&elqat=1&elqak=8AF512931A9D3060F4A93E1FC36635281ABF6CB5DF51A382344A375EE52C017C3E5F). Please contact GitHub [Support](https://app.github.media/e/er?s=88570519&lid=3338&elqTrackId=51ced43500f64a46924167a4a536829b&elq=c8e2b0ece4644da9b1fbbf27de7f9c73&elqaid=4309&elqat=1&elqak=8AF5D818E42E3357A6143F29D23F7AD3B3C16CB5DF51A382344A375EE52C017C3E5F) if you run into any problems or need help.
```

I updated cargo-dist:
```
cargo dist --version
dist 1.0.0-rc.1
```

and re-run `cargo dist init``

It refreshed dist-workspace.toml, main.waxs and release.yml

But I see that release.yml still uses `runs-on: "ubuntu-20.04"`

So, I think a new release is needed that updates that to use "ubuntu-24.04", or equivalent as per the GH email.

**Comment by duckinator** [comment]
Given that the brownout periods are less than 3 weeks away, yeah, we should definitely push an update using a newer version.

We try to use the oldest version that's still supported for a reasonable period of time, so it may be `ubuntu-22.04` (since that's [supported until April 2027](https://ubuntu.com/about/release-cycle)). (This approach allows us to support older operating systems without using unmaintained software.)

In the meantime, I'd recommend switching back to the latest stable dist (<1.0), and then you can switch to ubuntu-22.04 via [the `github-custom-runners` setting](https://opensource.axo.dev/cargo-dist/book/reference/config.html#github-custom-runners).

Related issue: #1613

**Comment by konstin** [comment]
Would it be possible to change the global, non-building steps to `ubuntu-latest`? In our case (ruff and uv), we build the actual artifacts in separate containers due to our glibc requirements (manylinux), so it's only the global steps that are on the old ubuntu

**Comment by mpizenberg** [comment]
Also interested in this. Is there an explanation to what must be temporarily changed while waiting for the dist upgrade? I’ve just had my CI fail today due to this. In particular what custom runners should I set in my `dist-workspace.toml` file for the following?

```toml
[dist.github-custom-runners]
aarch64-apple-darwin = ?
aarch64-unknown-linux-gnu = ?
aarch64-pc-windows-msvc = ?
x86_64-apple-darwin = ?
x86_64-unknown-linux-musl = ?
x86_64-pc-windows-msvc = ?
```

And are these customization enough, or do I need to manually change things somewhere else?

**Comment by jaybosamiya** [comment]
Brief note that it is ~2 weeks away from 20.04 being completely removed and only some hours away from the 3rd of the 4 brownouts.

I don't think a simple `sed 's/20.04/22.04/g` in this repo is sufficient, but I think it is _almost_ sufficient (maintainers would be better suited to making sure of other things that might need updates) but from a brief look through, I believe the only relevant places (other than the `sed` script) are:
- updating glibc version here:
https://github.com/axodotdev/cargo-dist/blob/c8ba950c63f9c38c77782912ec6cdb6807bd0fbd/cargo-dist/src/platform.rs#L314-L324
and
- removing the line here:
https://github.com/axodotdev/cargo-dist/blob/c8ba950c63f9c38c77782912ec6cdb6807bd0fbd/cargo-dist/src/platform/github_runners.rs#L16-L17

It is possible I might have missed some things, which is why I haven't opened a PR (which likely might need more effort to review than repeating above mentioned steps), but I'm happy to open a PR with the above steps if maintainers think it might help.

**Comment by DavisVaughan** [comment]
I believe we are going to require some kind of update from cargo-dist to keep CI running due to this.

First, note that GitHub extended the Ubuntu 20.04 deadline from April 1 -> April 15, so we have a few more days.
https://github.com/actions/runner-images/issues/11101

But I'd like add some specifics to what @konstin is saying and note that the `plan` and `build-global-artifacts` steps are locked to `ubuntu-20.04`, when really it feels like they can be `ubuntu-latest`. Even when you manually fix up all runners in your builds to use `runner = "ubuntu-latest"` as we did [here](https://github.com/posit-dev/air/pull/292), you get warnings about Ubuntu 20.04 usage in those two dist controlled steps:

<img width="1078" alt="Image" src="https://github.com/user-attachments/assets/802920e6-c5d1-4959-b9bd-d0afd10cd995" />

IIUC, these are going to fail come April 15, preventing us from doing a release.

---

I'd also like to request using `ubuntu-latest` for the default setup of `aarch64-pc-windows-msvc`. That currently sets up on a runner of `ubuntu-20.04`, but then uses a container, so IIUC it could just use `ubuntu-latest` since the build itself doesn't really rely on the exact runner version?
https://github.com/axodotdev/cargo-dist/blob/c8ba950c63f9c38c77782912ec6cdb6807bd0fbd/cargo-dist/src/backend/ci/github.rs#L678-L688

**Comment by DavisVaughan** [comment]
Okay so if you're just trying to "get by" and not fail on CI come April 15th, you can apply the changes in this PR to your own repos to get off `ubuntu-20.04`: https://github.com/posit-dev/air/pull/292

Depending on your specific needs:

- To move the `plan`, `build-global-artifacts`, `host`, and `announce` steps in `release.yml` to `ubuntu-latest`:

   ```toml
   [dist.github-custom-runners]
   global = "ubuntu-latest"
   ```

   Followed by `dist generate` to regenerate `release.yml`


- If you use `x86_64-unknown-linux-gnu` or `aarch64-unknown-linux-gnu` targets

   ```toml
   [dist.github-custom-runners.x86_64-unknown-linux-gnu]
   runner = "ubuntu-latest"
   ```

   What you put here is dependent on your specific needs. You could use `ubuntu-22.04` to target the oldest Ubuntu still supported natively by github runners. Our exact setup is

   ```toml
   [dist.github-custom-runners.x86_64-unknown-linux-gnu]
   runner = "ubuntu-latest"
   container = { image = "quay.io/pypa/manylinux_2_28_x86_64", host = "x86_64-unknown-linux-musl" }
   ```

   Which uses the Python Packaging Authority's manylinux container to compile against glibc 2.28, to ensure we have backwards compatible support for very old linux versions (back to RHEL 8 and Ubuntu 18.04). The `runner` ends up not mattering too much for us, so latest is fine.

- If one of your targets was `aarch64-pc-windows-msvc`, then you were also using `ubuntu-20.04` probably without knowing it. dist was smart enough to actually use a Linux runner here and cross compile to arm windows using cargo-xwin, but it's hardcoded to `ubuntu-20.04` so you'll need to inline the exact "real" specifications that dist was doing automatically, in addition to updating to `ubuntu-latest`. Since this is a container, I am somewhat confident the `runner` version doesn't matter too much:

   ```toml
   [dist.github-custom-runners.aarch64-pc-windows-msvc]
   # https://github.com/axodotdev/cargo-dist/blob/c8ba950c63f9c38c77782912ec6cdb6807bd0fbd/cargo-dist/src/backend/ci/github.rs#L678-L688
   runner = "ubuntu-latest"
   host = "x86_64-unknown-linux-gnu"
   container = { image = "messense/cargo-xwin", host = "x86_64-unknown-linux-musl", package_manager = "apt" }
   ```

**Comment by TilakMaddy** [comment]
@DavisVaughan Thanks for the suggestion. I had the same issue. Do you mind helping me a bit more ?

While the plan step seems to have worked, we are facing trouble in build local artifacts step https://github.com/Cyfrin/safe-hash-rs/actions/runs/14199593974

**Comment by DavisVaughan** [comment]
You're building for musl here:
https://github.com/Cyfrin/safe-hash-rs/blob/4dedd48e5c922ff2990e0a02c90358981e2f7197/dist-workspace.toml#L13

i.e. the `"x86_64-unknown-linux-musl"` there, so you probably need something like this

```toml
[dist.github-custom-runners.x86_64-unknown-linux-musl]
runner = "ubuntu-latest"
container = { image = "quay.io/pypa/manylinux_2_28_x86_64", host = "x86_64-unknown-linux-musl" }
```

ive never tested with musl though so im not sure.

I also see `"aarch64-unknown-linux-gnu"` there, so you also need

```toml
[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-latest"
container = { image = "quay.io/pypa/manylinux_2_28_x86_64", host = "x86_64-unknown-linux-musl" }
```

**Comment by TilakMaddy** [comment]
Thanks for your guidance @DavisVaughan ..although musl didn't work I did some research and tried this

```toml
[dist.github-custom-runners.x86_64-unknown-linux-musl]
runner = "ubuntu-latest"
container = { image = "quay.io/pypa/musllinux_1_2_x86_64", host = "x86_64-unknown-linux-musl" }
```
It worked

**Comment by andrewdavidmackenzie** [comment]
Workflows failing already due to the deprecation of 20.04

![Image](https://github.com/user-attachments/assets/8e5d9842-5ea0-4a4e-9303-1a77d4fd98eb)

**Comment by RandyMcMillan** [comment]
In the mean time:

generate the plan-dist-manifest.json locally.

note the --allow-dirty flag

```
dist host --steps=create --tag=v0.0.## --allow-dirty --output-format=json > plan-dist-manifest.json
```
```
git add plan-dist-manifest.json
```
```
git commit plan-dist-manifest.json -m plan-dist-manifest.json
```

by-pass the plan stage in your release.yml

example:
https://github.com/RandyMcMillan/gnostr/actions/runs/14686435538/job/41215634416

**Comment by TilakMaddy** [comment]
You can just add custom runners in dist toml and set it to ubuntu latest.

**Comment by eredotpkfr** [comment]
> You can just add custom runners in dist toml and set it to ubuntu latest.

Thank you! Changing `runs-on` keys on `release.yml` file with a `allow-dirty` configuration and using custom runners for a specific builds are solved my problem. This is a quick fix way to unblocking somethings
```toml
[dist]
# Ignore out-of-date contents
allow-dirty = ["ci"]

[dist.github-custom-runners]
x86_64-unknown-linux-gnu = "ubuntu-22.04"
```
> Commits from my project
> https://github.com/eredotpkfr/subscan/pull/323/commits/ab92b1dc4202c51b5f3ac6b91ace9f4b43df8c23
> https://github.com/eredotpkfr/subscan/pull/323/commits/7507284e3dbd11cc76a8124f3c21caf5584e5219

**Comment by andrewdavidmackenzie** [comment]
I modify my dist-workspace.tomk and run dist init, but it re-generates the same release.yml file as before, which still includes:

```
jobs:
  # Run 'dist plan' (or host) to determine what tasks we need to do
  plan:
    runs-on: "ubuntu-20.04"
    outputs:
```

So, still tries to run on 20.04 and fails.

I've tried to update dist using cargo install, but the build fails (see other issue sumbitted), so I cannot update dist either.

**Comment by brianheineman** [comment]
@andrewdavidmackenzie adding the following to `dist-workspace.toml` then re-running `dist init` appears to address for my projects:

```toml
[dist.github-custom-runners]
global = "ubuntu-latest"

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-latest"
```

you may need to add additional target triples if you are releasing more than just `x86_64-unknown-linux-gnu`
