### ISSUE TITLE
`github-custom-runners` option having no effect

### ISSUE THREAD

**Issue by justDeeevin** [axodotdev/cargo-dist#1827]
Trying to get my CI to work again now that ubuntu-20.04 is retired. https://github.com/axodotdev/cargo-dist/issues/1760#issuecomment-2859640210 is supposedly the correct way to work around this problem, but applying that change to my `dist-workspace.toml` and re-running both `dist init` and `dist generate` results in **no change to the release workflow**. Here's the contents of my dist config right now:
```toml
[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "aarch64-pc-windows-msvc",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
# Which actions to run on pull requests
pr-run-mode = "plan"

[dist.dependencies.apt]
libxi-dev = '*'
libxtst-dev = '*'

[dist.custom-github-runners]
global = "ubuntu-latest"

[dist.custom-github-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-latest"
```

Am I doing something wrong?
