### ISSUE TITLE
Support getting metadata fields from workspace

### ISSUE THREAD

**Issue by zkat** [axodotdev/cargo-dist#251]
![image](https://github.com/axodotdev/cargo-dist/assets/17535/5b2f2b1d-1d6b-4f64-b8c7-aebb0bc21f3f)

This happens because my Cargo.toml looks like this:

```toml
[package]
name = "orogene"
version = "0.3.25"
description = "`node_modules/` package manager and utility toolkit."
readme = "README.md"
build = "build.rs"
license = "Apache-2.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
```
