### ISSUE TITLE
Question: Why is the created action run on pull requests by default?

### ISSUE THREAD

**Issue by fritzrehde** [axodotdev/cargo-dist#494]
Hi, I noticed the auto-generated `release.yml` contains:
```yaml
on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
```
I am not sure why I would want to run the release action as checks on GitHub for each pull request. It's not like merging a pull request means the project should be updated to a new version. I find this being the default slightly confusing, and would like to know how to disable it. Obviously I can just delete the `pull_request:` line, but will this mean that on subsequent runs of `cargo dist` it will be added again?
Thanks!
