### ISSUE TITLE
allow user to configure tag "namespace"

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#758]
some users deploy from a workspace and namespace tags to coordinate different release trains for different parts of the workspace. this usually means they want a member-v0.0.0 style tag instead of the v0.0.0 tag that cargo-dist expects.

i propose the following config to generate the following workflow:

```toml
# Cargo.toml
tag-namespace = "customstring"
```

generates
```yml
# release.yml
on:
  push:
    tags:
      - 'customstring-**[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
```
