### ISSUE TITLE
Respect `publish = false`

### ISSUE THREAD

**Issue by Aloso** [axodotdev/cargo-dist#80]
My project containts two binary crates. One has this in the `Cargo.toml`:

```toml
[package]
# ...
publish = false
```

`cargo dist` builds both binary crates, but it should skip the one where `publish = false` is set.
