### ISSUE TITLE
Request for a way to override the package name

### ISSUE THREAD

**Issue by ChanTsune** [axodotdev/cargo-dist#832]
At present, it appears that cargo-dist does not provide a way to override the package.name property in Cargo.toml.

Here's one idea for implementing this:

```toml
[workspace.metadata.dist.override]
name = "..."
```
I think this method could also be applied to properties other than name.
